[build]
  command = "npm install"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.17.0"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
